import React, { useState } from 'react';
import { Button } from '../components/ui/Button';
import { Category } from '../types';
import { BlogService } from '../services/blogService';
import { FileUploadService } from '../services/fileUploadService';
import { PenTool, Layout, Image as ImageIcon, Sparkles, Upload, CheckCircle, AlertCircle } from 'lucide-react';
import { GoogleGenAI } from "@google/genai";
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';

// Define Validation Schema
const articleSchema = z.object({
  title: z.string().min(5, "Title must be at least 5 characters").max(100, "Title is too long"),
  category: z.nativeEnum(Category),
  excerpt: z.string().min(10, "Excerpt must be at least 10 characters").max(300, "Excerpt is too long"),
  content: z.string().min(50, "Content must be substantial (50+ characters)"),
  imageUrl: z.string().url("Featured image is required"),
  author: z.string().min(2, "Author name required")
});

type ArticleFormData = z.infer<typeof articleSchema>;

export const Admin: React.FC = () => {
  const [activeTab, setActiveTab] = useState<'create' | 'dashboard'>('dashboard');
  const [isGenerating, setIsGenerating] = useState(false);
  const [isUploading, setIsUploading] = useState(false);

  const { 
    register, 
    handleSubmit, 
    setValue, 
    watch, 
    reset,
    formState: { errors, isSubmitting } 
  } = useForm<ArticleFormData>({
    resolver: zodResolver(articleSchema),
    defaultValues: {
      title: '',
      category: Category.FASHION,
      excerpt: '',
      content: '',
      imageUrl: '', // This will be populated by upload
      author: 'Lumière Editor'
    }
  });

  // Watch values for preview or logic
  const watchedImageUrl = watch('imageUrl');
  const watchedTitle = watch('title');
  const watchedCategory = watch('category');

  // Handle File Upload
  const handleFileChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    try {
      setIsUploading(true);
      const url = await FileUploadService.uploadImage(file);
      setValue('imageUrl', url, { shouldValidate: true });
    } catch (error) {
      console.error("Upload failed", error);
      alert("Failed to upload image");
    } finally {
      setIsUploading(false);
    }
  };

  // Handle AI Generation
  const handleGenerateAI = async () => {
    if (!watchedTitle) {
      alert("Please enter a title first to generate content.");
      return;
    }

    try {
      setIsGenerating(true);
      
      // Check for API Key
      if (!process.env.API_KEY) {
          // Fallback simulation for demo
          setTimeout(() => {
              setValue("excerpt", "Generated by AI: A stunning exploration of silk textures that redefine modern luxury, capturing the essence of fluidity and grace in every stitch.", { shouldValidate: true });
              setValue("content", "Generated by AI: \n\nStart with a bold statement about fabric. \n\nDiscuss the history of silk in the 1920s. \n\nTransition to modern sustainable silk alternatives. \n\nConclude with upcoming runway trends featuring this material...", { shouldValidate: true });
              setIsGenerating(false);
          }, 1500);
          return;
      }

      const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
      const model = "gemini-2.5-flash";
      const prompt = `Write a high-fashion editorial excerpt (max 50 words) and a detailed outline/content (approx 300 words) for an article titled "${watchedTitle}" in the category "${watchedCategory}". Keep the tone luxurious, Vogue-like, and sophisticated.`;
      
      const response = await ai.models.generateContent({
          model: model,
          contents: prompt,
      });

      const text = response.text;
      const splitText = text.split('\n');
      const generatedExcerpt = splitText[0] || "AI generated content";
      const generatedContent = splitText.slice(1).join('\n');

      setValue("excerpt", generatedExcerpt, { shouldValidate: true });
      setValue("content", generatedContent, { shouldValidate: true });

    } catch (error) {
      console.error("AI Generation failed", error);
      alert("Failed to generate content. Please check console.");
    } finally {
      setIsGenerating(false);
    }
  };

  // Handle Submit
  const onSubmit = async (data: ArticleFormData) => {
    try {
      await BlogService.createArticle(data);
      alert('Article published successfully!');
      reset(); // Clear form
      setActiveTab('dashboard'); // Go back to dashboard
    } catch (error) {
      console.error("Submission failed", error);
      alert("Failed to publish article.");
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 pt-24 pb-12">
      <div className="container mx-auto px-6 max-w-6xl">
        <div className="mb-8 flex items-center justify-between">
            <div>
                <h1 className="text-3xl font-serif text-luxe-black">Editorial <span className="text-luxe-gold">Desk</span></h1>
                <p className="text-slate-500 text-sm">Manage content and curate the platform.</p>
            </div>
            <div className="flex gap-4">
                <button 
                    onClick={() => setActiveTab('dashboard')}
                    className={`flex items-center gap-2 px-4 py-2 rounded-md transition-colors ${activeTab === 'dashboard' ? 'bg-luxe-black text-white' : 'bg-white text-slate-600 hover:bg-gray-100'}`}
                >
                    <Layout size={18} /> Dashboard
                </button>
                <button 
                    onClick={() => setActiveTab('create')}
                    className={`flex items-center gap-2 px-4 py-2 rounded-md transition-colors ${activeTab === 'create' ? 'bg-luxe-black text-white' : 'bg-white text-slate-600 hover:bg-gray-100'}`}
                >
                    <PenTool size={18} /> New Article
                </button>
            </div>
        </div>

        {activeTab === 'dashboard' && (
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 animate-fade-in-up">
                <div className="bg-white p-8 shadow-sm border border-gray-100 rounded-lg">
                    <h3 className="text-slate-500 uppercase tracking-widest text-xs font-bold mb-2">Total Views</h3>
                    <p className="text-4xl font-serif text-luxe-black">1.2M</p>
                    <span className="text-green-500 text-sm font-semibold">+12% this week</span>
                </div>
                <div className="bg-white p-8 shadow-sm border border-gray-100 rounded-lg">
                    <h3 className="text-slate-500 uppercase tracking-widest text-xs font-bold mb-2">Active Articles</h3>
                    <p className="text-4xl font-serif text-luxe-black">84</p>
                    <span className="text-slate-400 text-sm">Latest posted 2h ago</span>
                </div>
                <div className="bg-white p-8 shadow-sm border border-gray-100 rounded-lg">
                    <h3 className="text-slate-500 uppercase tracking-widest text-xs font-bold mb-2">Subscribers</h3>
                    <p className="text-4xl font-serif text-luxe-black">45.2k</p>
                    <span className="text-green-500 text-sm font-semibold">+85 new today</span>
                </div>
                
                {/* Recent Activity Mock */}
                <div className="md:col-span-3 bg-white p-8 shadow-sm border border-gray-100 rounded-lg mt-6">
                    <h3 className="font-serif text-xl mb-6">Recent Publications</h3>
                    <div className="space-y-4">
                        {[1, 2, 3].map((i) => (
                            <div key={i} className="flex items-center justify-between border-b border-gray-100 pb-4 last:border-0 last:pb-0">
                                <div className="flex items-center gap-4">
                                    <div className="w-12 h-12 bg-gray-200 rounded overflow-hidden">
                                        <img src={`https://picsum.photos/seed/fashion${i}/100/100`} alt="thumb" className="w-full h-full object-cover" />
                                    </div>
                                    <div>
                                        <p className="font-bold text-luxe-black">Summer Essentials Vol. {i}</p>
                                        <p className="text-xs text-slate-500">Published by Elena V. • 2 days ago</p>
                                    </div>
                                </div>
                                <span className="text-xs font-bold uppercase tracking-wider bg-green-100 text-green-800 px-2 py-1 rounded">Live</span>
                            </div>
                        ))}
                    </div>
                </div>
            </div>
        )}

        {activeTab === 'create' && (
            <div className="bg-white p-8 md:p-12 shadow-sm border border-gray-100 rounded-lg max-w-3xl mx-auto animate-fade-in">
                <h2 className="text-2xl font-serif mb-8 text-center">Compose New Story</h2>
                
                <form onSubmit={handleSubmit(onSubmit)} className="space-y-8">
                    
                    {/* Title */}
                    <div>
                        <label className="block text-xs uppercase font-bold text-slate-500 tracking-widest mb-2">Headline</label>
                        <input 
                            {...register("title")}
                            type="text" 
                            className="w-full border-b-2 border-gray-200 py-3 text-xl font-serif focus:outline-none focus:border-luxe-gold transition-colors bg-transparent placeholder-gray-300"
                            placeholder="Enter an elegant headline..."
                        />
                        {errors.title && <p className="text-red-500 text-xs mt-1 flex items-center gap-1"><AlertCircle size={10} /> {errors.title.message}</p>}
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                        {/* Category */}
                        <div>
                            <label className="block text-xs uppercase font-bold text-slate-500 tracking-widest mb-2">Category</label>
                            <div className="relative">
                                <select 
                                    {...register("category")}
                                    className="w-full border-b-2 border-gray-200 py-3 text-sm focus:outline-none focus:border-luxe-gold bg-transparent appearance-none"
                                >
                                    {Object.values(Category).map(cat => (
                                        <option key={cat} value={cat}>{cat}</option>
                                    ))}
                                </select>
                            </div>
                        </div>

                        {/* Author */}
                        <div>
                            <label className="block text-xs uppercase font-bold text-slate-500 tracking-widest mb-2">Author</label>
                            <input 
                                {...register("author")}
                                type="text"
                                className="w-full border-b-2 border-gray-200 py-3 text-sm focus:outline-none focus:border-luxe-gold bg-transparent placeholder-gray-300"
                            />
                            {errors.author && <p className="text-red-500 text-xs mt-1 flex items-center gap-1"><AlertCircle size={10} /> {errors.author.message}</p>}
                        </div>
                    </div>

                    {/* Image Upload */}
                    <div>
                         <label className="block text-xs uppercase font-bold text-slate-500 tracking-widest mb-2">Cover Image</label>
                         
                         {/* Hidden Inputs */}
                         <input type="hidden" {...register("imageUrl")} />
                         <input 
                            type="file" 
                            accept="image/*" 
                            id="file-upload" 
                            className="hidden" 
                            onChange={handleFileChange} 
                         />

                         <div className="border-2 border-dashed border-gray-200 rounded-lg p-6 text-center hover:border-luxe-gold transition-colors relative bg-gray-50/50">
                            {watchedImageUrl ? (
                                <div className="relative w-full h-64 group">
                                    <img src={watchedImageUrl} alt="Preview" className="w-full h-full object-cover rounded-md" />
                                    <div className="absolute inset-0 bg-black/40 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity rounded-md">
                                        <label htmlFor="file-upload" className="cursor-pointer bg-white text-luxe-black px-4 py-2 rounded-full text-xs font-bold uppercase tracking-widest hover:bg-luxe-gold transition-colors">
                                            Change Image
                                        </label>
                                    </div>
                                    <div className="absolute top-2 right-2 bg-green-500 text-white rounded-full p-1">
                                        <CheckCircle size={16} />
                                    </div>
                                </div>
                            ) : (
                                <label htmlFor="file-upload" className="cursor-pointer flex flex-col items-center gap-2 py-8">
                                    {isUploading ? (
                                        <div className="w-8 h-8 border-2 border-luxe-gold border-t-transparent rounded-full animate-spin"></div>
                                    ) : (
                                        <>
                                            <Upload size={32} className="text-slate-300" />
                                            <span className="text-sm text-slate-500 font-serif">Click to upload editorial cover</span>
                                        </>
                                    )}
                                </label>
                            )}
                         </div>
                         {errors.imageUrl && <p className="text-red-500 text-xs mt-1 flex items-center gap-1"><AlertCircle size={10} /> {errors.imageUrl.message}</p>}
                    </div>

                    {/* Excerpt */}
                    <div className="relative">
                        <div className="flex justify-between items-end mb-2">
                             <label className="block text-xs uppercase font-bold text-slate-500 tracking-widest">Excerpt</label>
                             <button 
                                type="button" 
                                onClick={handleGenerateAI}
                                disabled={isGenerating || !watchedTitle}
                                className="text-xs flex items-center gap-1 text-luxe-gold hover:text-black transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                             >
                                <Sparkles size={12} /> {isGenerating ? 'Dreaming...' : 'Magic Generate'}
                             </button>
                        </div>
                        <textarea 
                            {...register("excerpt")}
                            rows={3}
                            className="w-full bg-gray-50 border border-gray-200 p-4 rounded text-sm leading-relaxed focus:outline-none focus:border-luxe-gold placeholder-gray-400"
                            placeholder="A brief, captivating summary..."
                        />
                        {errors.excerpt && <p className="text-red-500 text-xs mt-1 flex items-center gap-1"><AlertCircle size={10} /> {errors.excerpt.message}</p>}
                    </div>

                    {/* Full Content */}
                    <div>
                        <label className="block text-xs uppercase font-bold text-slate-500 tracking-widest mb-2">Full Content</label>
                        <textarea 
                            {...register("content")}
                            rows={12}
                            className="w-full bg-gray-50 border border-gray-200 p-4 rounded text-sm leading-relaxed focus:outline-none focus:border-luxe-gold font-serif placeholder-gray-400"
                            placeholder="Tell the story..."
                        />
                         {errors.content && <p className="text-red-500 text-xs mt-1 flex items-center gap-1"><AlertCircle size={10} /> {errors.content.message}</p>}
                    </div>

                    <div className="flex justify-end pt-6 border-t border-gray-100">
                        <Button type="submit" variant="primary" disabled={isSubmitting}>
                            {isSubmitting ? 'Publishing...' : 'Publish Editorial'}
                        </Button>
                    </div>
                </form>
            </div>
        )}
      </div>
    </div>
  );
};